package com.stinkelectronics.helpdesk.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
//test
@Entity
@Table(name="Account")
public class Account implements Serializable{
	
	//autogenerated sql side
	@Id
	private int UserAID;
	
	private String Password;
	private String Email;
	
	//map UserID
	@OneToOne
	@JoinColumn(name="FK_UserID")
	private Profile profile;
	
	public Account(){
		this.Password = "defaultpassword";
		this.Email = "defaultemail";
		
		this.profile = new Profile();
	}
	
}

