package com.stinkelectronics.helpdesk.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
//test
@Entity
@Table(name="Account")
public class Account implements Serializable{
	
	//autogenerated sql side
	@Id
	private int UserAID;
	
	private String Password;
	private String Email;
	private String FirstName;
	
	//map UserID
	@OneToOne
	@JoinColumn(name="FK_UserID")
	private Profile profile;
	
	public Account(String string, String string2, String string3){
		this.Password = "defaultpassword";
		this.Email = "defaultemail";
		this.FirstName = "defaultuser";
		
		this.profile = new Profile();
	}
	public String getFirstName() {
		return FirstName;
	}
	
	public void setFirstName(String name) {
		this.FirstName = name;
	}
	
	public String getPassword() {
		return Password;
	}
	
	public void setPassword(String pw) {
		this.Password = pw;
	}
	
	public String getEmail() {
		return Email;
	}
	
	public void setEmail(String email) {
		this.Email = email;
	}
}
	
}

